pipeline:
  build:
    image: registry.stationa.io/stationa/base:latest
    commands:
      - tox --sitepackages
  publish:
    image: plugins/docker
    registry: registry.stationa.io
    repo: registry.stationa.io/stationa/landgrab
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
      - ${DRONE_BRANCH}-latest
    when:
      event: push
  publish:
    image: plugins/docker
    registry: registry.stationa.io
    repo: registry.stationa.io/stationa/landgrab
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
