source:
  uri: https://data.cityofnewyork.us/api/geospatial/nqwf-w8eh?method=export&format=GeoJSON
  format: geojson

transform:
  tasks:
    - type: project
      schema:
        type: $.type
        properties.building_id: $.properties.bin
        properties.height_ft: $.properties.heightroof
        properties.year_built: $.properties.cnstrct_yr
        geometry: $.geometry

sink:
  uri: s3://stationa-shapes/buildings/us/ny/new_york_city.jsonlines
  params:
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
  format: jsonlines
