source:
  uri: http://data-lahub.opendata.arcgis.com/datasets/813fcefde1f64b209103107b26a8909f_0.zip
  format: shp

transform:
  tasks:
    - type: project
      schema:
        type: $.type
        properties.building_id: $.properties.BLD_ID
        properties.height_ft: $.properties.HEIGHT
        properties.base_elevation_ft: $.properties.ELEV
        geometry: $.geometry

sink:
  uri: s3://stationa-shapes/buildings/us/ca/los_angeles.jsonlines
  params:
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
  format: jsonlines
