source:
  uri: https://data.oaklandnet.com/api/geospatial/qvww-ev2w?method=export&format=GeoJSON
  format: geojson

transform:
  tasks:
    - type: project
      schema:
        type: $.type
        properties.building_id: $.properties.bldgid3
        properties.stories: $.properties.nostory
        geometry: $.geometry

sink:
  uri: s3://stationa-shapes/buildings/us/ca/oakland.jsonlines
  params:
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
  format: jsonlines
